manifest:
  version: "0.10"
  remotes:
    - name: nordic
      url-base: https://github.com/nrfconnect
  projects:
    - name: sdk-nrf
      path: nrf
      # We point to a branch on the Memfault fork of
      # NCS, which may have beta NCS changes for
      # Memfault currently under testing, but will
      # otherwise be a mirror of upstream NCS main.
      url: https://github.com/memfault/sdk-nrf.git
      revision: dogfood
      import: true
    - name: memfault-firmware-sdk
      url: https://github.com/memfault/memfault-firmware-sdk
      path: modules/lib/memfault-firmware-sdk
      revision: "1.8.1"
  self:
    path: firmware
