manifest:
  version: "0.10"
  remotes:
    - name: nordic
      url-base: https://github.com/nrfconnect
  projects:
    - name: sdk-nrf
      path: nrf
      # Symlinking to a local version doesn't play nice
      # with west, so instead point to our fork for now
      # TODO: Remove url and revision when this is no
      # longer needed
      url: https://github.com/memfault/sdk-nrf.git
      revision: gminn/lte-metrics
      import: true
  self:
    path: firmware
