name: Update Memfault
run-name: ${{ inputs.run_name }}

env:
  DEFAULT_PYTHON: 3.8

on:
  schedule:
    - cron: "8 0 * * *"
  workflow_dispatch:
    inputs:
      run_name:
        description: 'Name of run to identify it from other runs'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install needed packages
        run: |
          sudo apt-get update
          sudo apt-get install --no-install-recommends -y -qq \
          curl \
          ripgrep

      - name: Get latest Memfault SDK version
        run: |
          echo "SDK_VER=$(rg 'VERSION:\s(\d+\.\d+\.\d+)' \
            <(curl -sSL 'https://raw.githubusercontent.com/memfault/memfault-firmware-sdk/master/VERSION') -r '$1' --no-filename --no-line-number)" >> $GITHUB_ENV

      - name: Get Memfault SDK version in west.yml
        run: |
          echo "REPO_SDK_VER=$(yq '.manifest.projects[1].revision' west.yml)" >> $GITHUB_ENV

      - name: Update west.yml
        if: ${{ env.SDK_VER }} != ${{ env.REPO_SDK_VER }}
        run: |
          yq -i '.manifest.projects[1].revision = "${{ env.SDK_VER }}"' west.yml
          git status

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GH_PAT }}
          commit-message: |
            chore(memfault): update memfault sdk

            ### Summary

            Update the Memfault SDK

            ### Test Plan

            CI
          title: |
            chore(memfault): pull in latest memfault sdk
          base: main
          branch: github-actions/update-to-memfault-v${{ env.SDK_VER }}
          delete-branch: true
          team-reviewers: memfault/owners-mcu
